default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  socket: /var/lib/mysql/mysql.sock
  pool: 5
  username: root_icontract
  password: '120880'

#  database: tm2t_production
#  host: 192.168.20.33
#  port: 3306

development:
  <<: *default
  database: icontract_development

test:
  <<: *default
  database: icontract_test

production:
  <<: *default
  database: icontract_production



users_default: &users_default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  socket: /var/lib/mysql/mysql.sock
  pool: 5
  username: root_tm2
  password: '120880'


users_development: 
  <<: *users_default
  database: tm2t_development

users_test:
  <<: *users_default  
  database: tm2t_test

users_production:
  <<: *users_default  
  database: <%= ENV["USERS_PRODUCTION_DATABASE"] %>
